Setup and Configure Server, Authentication, and User Management
chimdie/shorttiee pull request #13
Opened 2024-11-17 19:02 UTC by micaiah-effiong

## Summary of Changes:

- Server Setup & Configuration:
  - Added basic instructions to the README for setting up the server.
  - Moved configuration files into a `config` folder for better organization.
  - Setup database using `better-sqlite3` and added related database setup files.

- Authentication & User Management:
  - Implemented user registration and login endpoints.
  - Added OTP verification with time-to-live (TTL) for better security.
  - Introduced JWT signing and verification utilities.
  - Added features for resetting passwords and changing user passwords with re-authentication.
  - Validated email domains before registration.

- Database Enhancements:
  - Added necessary migrations and updated queries for user and authentication tables.
  - Implemented database triggers and fixed foreign key references.
  - Created async wrappers for controller functions and added utility functions for type assertions.

- Documentation:
  - Improved and fixed typos in documentation, especially related to response DTO.
  - Added API documentation for authentication routes.
  - Updated setup documentation for ease of use.

- Miscellaneous:
  - Refined logging for better error tracing.
  - Updated `.gitignore` to ignore variant `.env` files and unnecessary directories.

2024-11-18 14:23 UTC, chimdie requested changes
1. Update env sample on the Readme
2.  Update `/auth/register` reponse
<img width="600" alt="Screenshot 2024-11-18 at 2 38 00 PM" src="https://github.com/user-attachments/assets/cb74712b-7093-4c2c-aa53-d8159871f294">

2024-11-20 10:48 UTC, sammy-code98 commented
### Issue running setting up and running the server on my computer

Setting up and running the server on my local PC has proven abortive. I have attached a screenshot of the error below.

![npm](https://github.com/user-attachments/assets/3ab69510-c9e8-4aa1-bad7-ebc0bef56c3b)

The error occurs when I try to run `npm install`

it is worth noting that isolating or removing the `better-sqlite3` package from the project's dependencies means that  `npm install` runs successfully without errors

### PC /Environment specs
- Zorin/Ubuntu OS
- Node Version: v22.11.0
-Npm version: 10.9.0

2024-11-20 10:53 UTC, micaiah-effiong commented
> ### Issue running setting up and running the server on my computer
> Setting up and running the server on my local PC has proven abortive. I have attached a screenshot of the error below.
> 
> ![npm](https://private-user-images.githubusercontent.com/46542941/388058986-3ab69510-c9e8-4aa1-bad7-ebc0bef56c3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDAyMjcsIm5iZiI6MTczMjA5OTkyNywicGF0aCI6Ii80NjU0Mjk0MS8zODgwNTg5ODYtM2FiNjk1MTAtYzllOC00YWExLWJhZDctZWJjMGJlZjU2YzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEwNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOGJlYmJmZjYxNjgwMjE2YTdlYjhmY2FlYWIwNWQxN2NkNTRiYmRhMzE4MmM0YzA4NzgxYzY2NmM0ZWQyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.50nUa_3WP81CstAyQk8mo22vQ8m9EL-4v4vmE13Pihw)
> 
> The error occurs when I try to run `npm install`
> 
> it is worth noting that isolating or removing the `better-sqlite3` package from the project's dependencies means that `npm install` runs successfully without errors
> 
> ### PC /Environment specs
> * Zorin/Ubuntu OS
> * Node Version: v22.11.0
> * Npm version: 10.9.0

What version of Ubuntu are you using?

2024-11-20 10:59 UTC, sammy-code98 approved these changes
LGTM except for the issue with me running it localluy

2024-11-20 10:59 UTC, sammy-code98 commented on server/src/docs/schemas.docs.ts
Noticed that this file is empty

2024-11-21 08:31 UTC, sammy-code98 commented
### Issue running setting up and running the server on my computer

This issue has been resolved

### Cause of issue
A  system library `libc.so.6` required to run the `better-sqlite3` package was missing in the OS environment. The  `GLIBC` version `2.28`  available didnt match what was required to run the package `2.29`.

ps:  upgrading the zorin os to a version that comes with the right versions proved abortive as zorin doesnt support os upgrade from the terminal

### Solution
Use another os that has the `libc.so.6` and `GLIBC 2.29` installed.


### Server now runs well

![goodnpm](https://github.com/user-attachments/assets/38b0c96e-5113-4ac2-bf32-c77e461a9383)


![Screenshot from 2024-11-21 09-14-11](https://github.com/user-attachments/assets/ce9eea90-ce2e-4699-9e4a-eb8828f7c4ff)

2024-11-22 07:22 UTC, merged