WIP:Feat/UI/shortletpage
chimdie/shorttiee pull request #14
Opened 2024-11-18 23:24 UTC by sammy-code98

2024-11-19 11:33 UTC, chimdie requested changes

2024-11-19 11:33 UTC, chimdie commented on host/src/App.tsx
>  import NotFound from "./components/NotFound";
```suggestion
import NotFound from "@/components/NotFound";
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/action-popover.tsx
1. Use [Next UI Dropdown](https://nextui.org/docs/components/dropdown) component instead of Popover
2. Move into the table component and remove this file

2024-11-19 11:33 UTC, chimdie commented on host/src/components/TablePagination/index.tsx
This should just be a file and not inside a folder/

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
Move this file into the main [shortlet file ](https://github.com/chimdie/shorttiee/pull/14/files#diff-b1f1bcdf24c4f51fecec8bbb6c07a9aab2ad6005d2aa0adba292f76adf172c88)

2024-11-19 11:33 UTC, chimdie commented on host/tailwind.config.js
> +        black: "#000000",
These are already tailwind default colors, right?

2024-11-19 11:33 UTC, chimdie commented on host/src/pages/Dashboard/Shortlet/editShortlet.tsx
If the create shorltet is on a modal, the edit should equally be one, right?

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                <TableRow className="bg-white border-y-5 border-grey_100 " key={item._id}>
Make the entire `TableRow` clickable and not the just a `TableCell`

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                    <span className="line-clamp-2 max-w-full overflow-hidden text-ellipsis whitespace-normal text-xs md:text-sm text-black font-normal cursor-pointer">
```suggestion
                    {item.name}
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                    <span className="text-xs md:text-sm font-normal text-black">{item.type}</span>
```suggestion
                    {item.type}
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                    <span className="text-xs md:text-sm font-normal text-black">
```suggestion
                    {item.location}
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                    <span className="text-xs md:text-sm font-normal text-black">{item.price}</span>
```suggestion
                    {item.price}
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                    <Chip radius="sm" className={getStatusClass(item.status)}>
```suggestion
                    <Chip radius="sm" className={`${getStatusClass(item.status)} text-xs font-normal capitalize`}>
```

2024-11-19 11:33 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +                      <span className="text-xs font-normal capitalize">{item.status}</span>
```suggestion
                      {item.status}
```

2024-11-19 11:35 UTC, chimdie requested changes

2024-11-19 11:35 UTC, chimdie commented on host/src/components/Shortlet/shortlet-table.tsx
> +          <Button className="bg-shorttiee_primary font-medium" onClick={addShortletModal.onOpen}>
Use [Next UI button](https://nextui.org/docs/components/button)

2024-11-22 14:18 UTC, sammy-code98 commented on host/src/pages/Dashboard/Shortlet/editShortlet.tsx
The edit option as a modal might prevent the ideal navigation process especially as breadcrumbs are already implemented. and modals can have bad UX when editing content I think

2024-11-25 20:50 UTC, chimdie approved these changes

2024-11-25 20:51 UTC, merged