listings
chimdie/shorttiee pull request #28
Opened 2024-12-01 19:56 UTC by micaiah-effiong

2024-12-06 21:24 UTC, chimdie requested changes

2024-12-07 11:11 UTC, sammy-code98 approved these changes
LGTM

2024-12-07 17:41 UTC, micaiah-effiong commented on server/db/migrations/20241120145157_create_listings.sql
> +  status TEXT CHECK(status IN ("AWAITING_REVIEW","REJECTED","APPROVED")) NOT NULL,
`AWAITING_REVIEW` is more descriptive of the status. `PENDING` is just too generic

2024-12-08 04:50 UTC, chimdie approved these changes

2024-12-08 07:03 UTC, merged