Feat/UI/account
chimdie/shorttiee pull request #31
Opened 2024-12-03 21:53 UTC by sammy-code98

2024-12-04 11:56 UTC, chimdie requested changes

2024-12-04 11:56 UTC, chimdie commented on host/src/App.tsx
> +import Account from "./pages/Dashboard/Account";
```suggestion
import Account from "@/pages/Dashboard/Account";
```

2024-12-04 11:56 UTC, chimdie commented on host/src/App.tsx
> +import Notification from "./pages/Notification";
```suggestion
import Notification from "@/pages/Notification";
```

2024-12-04 11:56 UTC, chimdie commented on host/src/components/LogoutModal.tsx
> +              <div className="rounded-full bg-white w-10 h-10 flex justify-center items-center">
```suggestion
              <div className="rounded-full bg-white w-10 h-10 flex justify-center items-center aspect-square">
```

2024-12-04 11:56 UTC, chimdie commented on host/src/components/LogoutModal.tsx
> +              fullWidth={true}
```suggestion
              fullWidth
```

2024-12-04 11:56 UTC, chimdie commented on host/src/components/LogoutModal.tsx
> +              fullWidth={true}
```suggestion
              fullWidth
```

2024-12-04 11:56 UTC, chimdie commented on host/src/types/routes.ts
> +  account: "/account",
```suggestion
  account: "/profile",
```

2024-12-05 07:54 UTC, micaiah-effiong commented
Move this `hook` to a separate file. 
https://github.com/chimdie/shorttiee/blob/a724e9c00dd5e9b06e57f1af01beeed7aae89b6f/host/src/components/ui/sidebar.tsx#L34-L41
It currently affects fast refresh during development
<img width="386" alt="image" src="https://github.com/user-attachments/assets/78d78de5-f293-4673-9833-2b6bee29dbaf">

2024-12-05 08:21 UTC, micaiah-effiong commented
@sammy-code98 side-bar active state is removed on-hover

2024-12-05 17:03 UTC, sammy-code98 commented
> Move this `hook` to a separate file.
> 
> https://github.com/chimdie/shorttiee/blob/a724e9c00dd5e9b06e57f1af01beeed7aae89b6f/host/src/components/ui/sidebar.tsx#L34-L41
> 
> 
> It currently affects fast refresh during development
> <img alt="image" width="386" src="https://private-user-images.githubusercontent.com/52747707/392707543-78d78de5-f293-4673-9833-2b6bee29dbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTg0NzAsIm5iZiI6MTczMzQxODE3MCwicGF0aCI6Ii81Mjc0NzcwNy8zOTI3MDc1NDMtNzhkNzhkZTUtZjI5My00NjczLTk4MzMtMmI2YmVlMjlkYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE3MDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTFlNTlhOTliNmQzNGNjY2ViMjA3MzZjNGNiNWJjZDBlMjc5NjgxYzI3ZDQ2OWZkYmM2Nzk3MTM2MzlhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a9ytYGDMc5uK5ZCUmnYmP3rcnEkDa9VIt-XI54gLtdg">

@micaiah-effiong  resolved this earlier on , you can review

2024-12-05 20:20 UTC, chimdie approved these changes

2024-12-05 20:21 UTC, merged