Implemented file limit
chimdie/shorttiee pull request #41
Opened 2024-12-11 16:50 UTC by micaiah-effiong

closes #30

2024-12-12 11:30 UTC, sammy-code98 approved these changes
Noticed it took a bit long to process a large file (4 gb) I tried uploading before I got the error message. not sure if it has anything to do with my network strength

Aside that , everything else LGTM

2024-12-12 11:30 UTC, sammy-code98 commented on server/src/dto/env.dto.ts
> +  UPLOAD_PATH: z.string().default(os.tmpdir()),
Does this mean we get to add this value to our .env file @micaiah-effiong ?

2024-12-12 12:28 UTC, chimdie requested changes

2024-12-12 12:28 UTC, chimdie commented on server/src/config/db.config.ts
> +// db.pragma("journal_mode=WAL");
remove comments

2024-12-14 09:03 UTC, sammy-code98 approved these changes

2024-12-15 12:09 UTC, chimdie approved these changes

2024-12-15 12:10 UTC, merged